### ISSUE TITLE
relying on summary element in the feed to determine event type doesnt work for linked events

### ISSUE THREAD

**Issue by humblelistener** [JustGiving/JustGiving.EventStore.Http#10]
Subscriber implementation relies on [message.Summary](https://github.com/JustGiving/JustGiving.EventStore.Http/blob/master/src/JustGiving.EventStore.Http.SubscriberHost/EventStreamSubscriber.cs#L175-L189).

As we are encountering, both Evenstore version 3.3.0 & 3.2.0 sets value of Summary for linked events as "$>" (shown in the below pictures).

This causes subscriber listening to streams with linked events to fail (they are not able to resolve handlers from the summary value "$>").

![resolvelinks-false](https://cloud.githubusercontent.com/assets/2118714/11210236/c0f11b3e-8d7a-11e5-983e-9f95abf77754.png)
![resolvelinks-true](https://cloud.githubusercontent.com/assets/2118714/11210241/cab21592-8d7a-11e5-92a1-4724c6f88402.png)

**Comment by humblelistener** [comment]
I have a fix at https://github.com/JustGiving/JustGiving.EventStore.Http/compare/master...PageUpPeopleOrg:fixing-linked-events

It uses "?embed=rich" query as [documented here](http://docs.geteventstore.com/http-api/3.2.0/reading-streams/) and relying on eventType element.

I am also raised a event store support ticket to understand whether this a bug or an intentional change in behavior.

**Comment by humblelistener** [comment]
Here is the response from event store support about the summary element.
Thinking it gives a fair reason to consider using the query string. Any objections, comments?

![capture](https://cloud.githubusercontent.com/assets/2118714/11462982/1429946c-9770-11e5-86f7-a08efbc6b876.PNG)

**Comment by spadger** [comment]
Sorry,
I haven't been in a position to look at it recently, due to family commitments.  Let me look at it today; I would like to find out why our internal services haven't gone awry, because we are using this software with ES3.2.2

**Comment by humblelistener** [comment]
more updates from event store support - even referring to this discussion

![image](https://cloud.githubusercontent.com/assets/2118714/11469501/d2f01fa8-97aa-11e5-93e9-bc3b8df550ec.png)

**Comment by spadger** [comment]
Hi P (sorry, I don't have your name),

Your changes look good; would you like to submit the pull request so that you can be credited?  I can create it otherwise.  Thanks for your help too!

Jon

**Comment by humblelistener** [comment]
cool.. I am Karthik (@humblelistener) by the way
