### ISSUE TITLE
Prevent potential deadlocks by ConfigureAwait(false) in async methods

### ISSUE THREAD

**Issue by robvdlv** [JustGiving/JustGiving.EventStore.Http#19]
I see no use of .ConfigureAwait(false) in the libraries async methods.
A potential issue here is that clients may end up with a deadlock unintendedly.

This can be migitated by explicitly configuration continuation behavior of async tasks so that it does not resume on calling the context.

For details see:
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
http://menge.io/2015/05/07/async-pitfalls-dot-net/

**Comment by spadger** [comment]
Hi,

Good point.  I created a branch issue-19 - does that seem fair?  Context-resumption on the connection is configurable, but the event handlers are hard-coded to ConfigureAwait(false) since they are just kicked off from a timer

**Comment by robvdlv** [comment]
Hi,

Thanks for your quick response and picking this up.

I see how configuring the context-resumption on the connection could work, but am thinking about in what use case(s) one would want to use it. Also, would it make sense to default to not resuming the context, as its the safer and more performant version?

Cheers

**Comment by spadger** [comment]
Agreed.  I was thinking about asp.net users (for example) who would not want to lose their SynchronisationContext, but I didn't realise that it is preserved at the boundary with this code.  Updating the code now...

**Comment by robvdlv** [comment]
Cool thanks.

Added pull request for some configurations where you may have missed them.
