### ISSUE TITLE
Defining custom event types (other than CLR full type name)

### ISSUE THREAD

**Issue by robvdlv** [JustGiving/JustGiving.EventStore.Http#21]
Hi,

I like how you guys made it easy for read subscriptions of events, to bind event types to CLR types.
In our usage of the library, what we're missing is to be able to define an event type directly when writing events to the ES.

```NewEventData``` does provide some convenience factory methods, but it forces derivation of the event type to the CLR type fullname, based on the generic type argument provided to those factory methods.

What can we do to be able to provide the event type ourselves?

One way could be to modify the factory methods so an overload is provided to be explicit about the event type, however this may break current API.
Alternatively a builder could solve sensible defaults and per use case creation of the event.

I'd like to hear what are your ideas on this?

Rob

**Comment by spadger** [comment]
Hi Rob,

I see no reason why NewEventData's constructor can't be made public if that's what you need.  What do you mean by 'sensible defaults' though?  I think that opening up the constructor will allow you to create events however you need them.

Jon

**Comment by robvdlv** [comment]
Hi,

Was doubting whether that was something you'd consider; Yes that would cut it :)
See pull.

Rob

**Comment by robvdlv** [comment]
Was the build issue due v6 syntax or due me breaking it?

**Comment by spadger** [comment]
Works on my box™ We have overhauled our build agents and this project just needs a little TLC
________________________________
